version: 0.2

phases:

  build:
    on-failure: ABORT
    commands:
    - |
      DEVBUCK=$(aws ssm get-parameter --name /uc3/mrt/config-bucket-dev --query Parameter.Value --output text)
      aws s3 cp *manifest.yaml s3://${DEVBUCK}/uc3/mrt/mrt-ecs-manifest/
